name: CI-CD-Project

# Run this workflow every time a new commit pushed to your repository on the master branch
on:
  push:
    branches:
      - main

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided.
  employees-app:
    #Job name
    name: Build and push Docker image to Docker hub
    #Set the type of machine to run on.
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine.
      -
        name: Checkout
        uses: actions/checkout@v2
      #Install static QEMU binaries to run builders
      # for architectures other than the host.
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # The docker/setup-buildx action configures buildx,
      # which is a Docker CLI plugin that provides enhanced build capabilities.
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      #Authenticate to Docker Hub with credentials set in the secrets tab.
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ dockerhub.USERNAME }}
          password: ${{ dockerhub.PASSWORD }}
      #Build and push the image to Docker hub with the defined tag.
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mv/employees-app:latest